apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Default project for general applications"

  sourceRepos:
    - "git@github.com:pawan-97/kelm.git
    - "*"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
