{{- range .Values.applicationSets }}
{{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ $.Values.global.repoURL }}
        revision: {{ $.Values.global.targetRevision }}
        directories:
          - path: "clusters/{{ .name }}/*"
  template:
    metadata:
      name: "{{`{{path.basename}}`}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default-apps
      source:
        repoURL: {{ $.Values.global.repoURL }}
        targetRevision: {{ $.Values.global.targetRevision }}
        path: "{{`{{path}}`}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{path.basename}}`}}"
      syncPolicy:
        {{- toYaml $.Values.global.syncPolicy | nindent 8 }}
{{- end }}
{{- end }}
